# NAND Flash Configuration
nand_config:
  page_size: 16384  # Page size in bytes
  block_size: 4194304  # Block size in bytes
  num_blocks: 2048  # Number of blocks
  num_planes: 2  # Number of planes

# Optimization Configuration
optimization_config:
  error_correction:
    algorithm: "bch"  # Error correction algorithm (bch, ldpc)
    bch_params:
      m: 8
      t: 4
    # strength: 8  # Error correction strength (number of correctable bits)
  compression:
    algorithm: "lz4"  # Compression algorithm (lz4, zstd)
    level: 3  # Compression level (1-9)
  caching:
    capacity: 1024  # Cache capacity in MB
    policy: "lru"  # Cache replacement policy (lru, lfu, random)
  parallelism:
    read_threads: 4  # Number of parallel read threads
    write_threads: 2  # Number of parallel write threads

# Firmware Configuration
firmware_config:
  version: "1.0.0"  # Firmware version
  read_retry: true  # Enable read retry mechanism
  data_scrambling: true  # Enable data scrambling

# NAND Characterization Configuration
characterization_config:
  sample_size: 1000  # Number of sample points for characterization
  erase_threshold: 1000  # Threshold for erase count analysis
  data_retention: 1  # Data retention time in years

# Logging Configuration
logging:
  level: "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "logs/optimization_tool.log"  # Log file path
  max_size: 10485760  # Maximum log file size in bytes
  backup_count: 5  # Number of backup log files to keep

# User Interface Configuration
ui_config:
  theme: "light"  # UI theme (light, dark)
  font_size: 12  # Font size in pixels
  window_size: [800, 600]  # Window size [width, height]