# NAND Flash Configuration
nand_config:
  page_size: 4096   # Page size in bytes
  block_size: 256   # pages per block
  num_blocks: 1024
  oob_size: 128
  num_planes: 1

# Optimization Configuration
optimization_config:
  error_correction:
    algorithm: "bch"
    bch_params:
      m: 8
      t: 4
    strength: 4  # Error correction strength (number of correctable bits)
  compression:
    algorithm: "lz4"
    level: 3
    enabled: true
  caching:
    capacity: 1024
    policy: "lru"
    enabled: true
  parallelism:
    max_workers: 4
  wear_leveling:
    wear_level_threshold: 1000

# Firmware Configuration
firmware_config:
  version: "1.1.0"
  read_retry: true
  max_read_retries: 3
  data_scrambling: false

# Bad Block Management Configuration
bbm_config:
  max_bad_blocks: 100

# Wear Leveling Configuration
wl_config:
  wear_leveling_threshold: 1000

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/nand_optimization.log"
  max_size: 10485760
  backup_count: 5

# User Interface Configuration
ui_config:
  theme: "light"
  font_size: 12
  window_size: [1200, 800]

# Simulation Configuration
simulation:
  enabled: true  # Use simulator by default for safety
  error_rate: 0.0001
  initial_bad_block_rate: 0.002