---
# Test cases for the 3D NAND Optimization Tool
test_cases:
  - name: BasicReadWrite
    description: Test basic read/write operations
    test_methods:
      - name: test_write_read_basic
        sequence:
          - type: write
            block: 10
            page: 0
            data: "Hello, World!"
          - type: read
            block: 10
            page: 0
        expected_output: "Hello, World!"
      
      - name: test_erase_block
        sequence:
          - type: erase
            block: 11
          - type: read
            block: 11
            page: 0
        expected_output: ""  # Erased block should return empty/erased state

  - name: BadBlockHandling
    description: Test bad block management
    test_methods:
      - name: test_bad_block_detection
        sequence:
          - type: status
            block: 10
          - type: write
            block: 10
            page: 0
            data: "Test data"
          - type: read
            block: 10
            page: 0
        expected_output: "Test data"
      
      - name: test_bad_block_replacement
        sequence:
          - type: status
            block: 1022  # High block number that might be bad
          - type: status
            block: 1023
        expected_output: {}  # Any valid status object

  - name: WearLeveling
    description: Test wear leveling
    test_methods:
      - name: test_wear_leveling_tracking
        sequence:
          - type: erase
            block: 20
          - type: erase
            block: 20
          - type: erase
            block: 20
          - type: status
            block: 20
        expected_output: {"block_info": {"erase_count": 3}}
      
      - name: test_wear_distribution
        sequence:
          - type: erase
            block: 30
          - type: erase
            block: 30
          - type: erase
            block: 31
          - type: status
        expected_output: {}  # Any valid status object

  - name: ErrorCorrection
    description: Test error correction capabilities
    test_methods:
      - name: test_data_integrity
        sequence:
          - type: write
            block: 40
            page: 0
            data: "Error correction test data with a reasonably long string to ensure ECC has something to work with."
          - type: read
            block: 40
            page: 0
        expected_output: "Error correction test data with a reasonably long string to ensure ECC has something to work with."